sainnhe/everforest

alfred/README.md

I thought it would treat the file as a download like it treats Alfred workflows, but it doesn't. This link will show the actual file.

Fix alfred theme download link

---

colors/everforest.vim

Hi! I would like to add explicit support for [mini.nvim](https://github.com/echasnovski/mini.nvim).
Basic choices are taken from highlight groups to which 'mini.nvim' makes links by default or from analogous plugins.
Differences from default linked groups:
- 'mini.cursorword' is linked to `LspSignatureActiveParameter`.
- 'mini.indentscope' is based on 'Indent Blankline'.
- 'mini.jump' is based on 'clever-f'.
- 'mini.jump2d' is based on 'Hop'. Using `nocombine` to be consistent (not have italic labels on italic text).
- 'mini.starter' is based on 'Dashboard' and personal choices:
- `MiniStarterItemBullet` is as border.
- `MiniStarterItemPrefix` and `MiniStarterQuery` are based on "warning" and "info" diagnostic colors to be opposite of each other.
- `MiniStarterSection` is linked to …

feat(plugin): optimize `echasnovski/mini.nvim`

---

colors/everforest.vim

Fixes the exuberance of green-aqua shade in Lua tables when Treesitter highlighting is enabled.
Addresses my concern with Lua tables described in https://github.com/sainnhe/everforest/issues/74#issuecomment-1214135710
Before
After

lua/ts: Adjust highlight of fields and constructors

---

colors/everforest.vim

Fixes the exuberance of green-aqua shade in YAML documents when Treesitter highlighting is enabled.
Addresses my concern with YAML keys and values described in https://github.com/sainnhe/everforest/issues/74.
I picked `Orange` because that's what `yamlKey` is currently set to, but I see this color was copied from gruvbox-material, so let me know if you want me to change it to something else :) 
Fixes #74
(my concerns are only for YAML and [Lua](https://github.com/sainnhe/everforest/issues/75), I don't think any other action is needed for other languages)
Before
After

yaml/ts: Adjust highlight of keys and string values

---

colors/everforest.vim

Adjusts syntax highlight groups for the `toml` filetype to have Green as the dominant color instead of Orange.
Because a large portion of the symbols in a TOML document are _strings_, I highlighted these using the Foreground color to avoid overwhelming the reader with too much of a single warm color.
Before
After

toml/ts: Switch to Green as dominant color

---

colors/everforest.vim

The current highlighting for the `json` filetype was borrowed from Gruvbox Material, and has Orange as dominant color.
This doesn't fit very well with Everforest's general Green direction, so I propose we tweak the colors to make them more subtle, with a dominant of green/beige.
Because a large portion of the symbols in a JSON document are _strings_, I highlighted these using the Foreground color to avoid overwhelming the reader with too much of a single warm color.
Before
After

json/ts: Switch to Green as dominant color

---

colors/everforest.vim

Tackles a few more YAML highlight groups that were not covered in #76.
Depending on the YAML syntax enabled by the user, highlight groups may have different names. For example:
- Keys are `yamlBlockMappingKey` in Vim's core syntax, but `yamlKey` in [stephpy/vim-yaml](https://github.com/stephpy/vim-yaml) (a custom YAML syntax that was popular on older Vim versions)
- Treesitter doesn't make any distinction between a String and a Scalar, but the core Vim syntax does.
- `yamlConstant` includes both booleans and null values in core Vim syntax, but in Treesitter syntax they are distinct
This PR provides consistent highlighting regardless of the syntax method:
- Keys are Green
- String values are Fg
- Built-in constants (booleans, null) are orange italic to differentiate from numbers, which are …

yaml: Ensure consistent highlighting across syntaxes

---

colors/everforest.vim

Since [v8.2.3117](https://github.com/vim/vim/commit/90df4b9d423485f7db16e3a65cab4f14edc815ae), Vim ships with the syntax file from fatih/vim-go, which has richer, more granular syntax highlight groups.
Because Polyglot was using this exact syntax file, the polyglot-specific section can now be merged with the regular Go syntax.
Go is my main programming language and I tried to make sensible choices in the additional highlight groups provided by the current Vim syntax (with corresponding Treesitter groups):
- built-in function calls -> same as normal function calls, but _italic_ (if enabled)
- built-in types -> same as custom types, but _italic_ (if enabled)
- namespaces (Treesitter only) -> Fg instead of TSNamespace (YellowItalic) to avoid a dominance of yellow on screen. We refer to …

go: Update groups based on current Vim built-in syntax

---

colors/everforest.vim

Fixes #83
Pinging @xmready for feedback.
Before
After

js: Highlight template literals like strings

---

colors/everforest.vim

In #76 and #77, highlights for the JSON and YAML file types were updated to move the green tones towards the left side (keys) to avoid a dominance of green across the screen, since JSON and YAML are typically mainly composed of strings.
I noticed that a subtle difference remains between the Vim and Treesitter highlights: escape characters — such as `\n`, `\t`, etc. — are highlighted as Yellow (_SpecialChar_) with Vim highlights, but as Green (_TSStringEscape_) with Treesitter highlights. This is expected because, [by design](https://github.com/sainnhe/gruvbox-material/issues/119), strings default to Green with Vim highlights, and Aqua with Treesitter highlights. However, strings are Foreground in both YAML and JSON documents, so suggest to use a color coding which differs from fields to …

fix(yaml/json): special highlight for escape chars

---

colors/everforest.vim

Git commit summaries are currently Red, which appears to have been directly inherited from [Gruvbox-Material](https://github.com/sainnhe/gruvbox-material/blob/master/colors/gruvbox-material.vim#L2677).
While this color might work well with the "retro groove" feeling of Gruvbox, it feels a bit out of place in the "green, calm" Everforest theme:
- Everforest usually uses red for short keywords (_func_, conditionals, etc.)
- Long sentences in red tend to look like errors
I suggest we change this to the dominant color of the scheme: Green.
Before
After

feat(git): highlight commit summary in green

---

colors/everforest.vim

Fixes #87
Re-link LspSaga's highlight groups that [currently link to undercurl groups](https://github.com/glepnir/lspsaga.nvim/blob/0797b968325ee4dc8dc68e124a8d9a18e6a81888/plugin/lspsaga.lua#L41-L48) to core colors to avoid undercurl on popup text and borders, as seen in #87.
Before
After

fix(lspsaga): Suppress undercurl in text and borders

---

colors/everforest.vim

In https://github.com/sainnhe/everforest/pull/82, Javascript syntax highlight groups were optimized for "classic" Vim.
This PR suggests two minor additional optimisations specifically for Treesitter highlighting:
- `include` are purple to differentiate them from other keywords, which are all red
- `constructor` are yellow to differentiate them from functions, which are green
Before
After

feat(js): Treesitter hl for includes and constructors

---

colors/everforest.vim

There is no more distinction between names of capture groups and names of highlight groups starting with neovim/neovim#19931.
Fixes #89
_not applicable_

feat(ts): support Neovim 0.8 Treesitter hl groups

---

colors/everforest.vim

VertSplit is deprecated in Neovim in favour of WinSeparator. Although the two are currently linked, we replicate this link here explicitly to avoid future issues in Neovim due to the deprecation.
Not applicable

feat: link WinSeparator highlighting group

---

colors/everforest.vim

Closes #95
**tl;dr:** `TSStructure` / `@structure` was removed from Neovim because it:
- wasn't used
- had unclear semantics, possibly overlapped with `@namespace`

chore(ts): clear hl for removed @structure group

---

colors/everforest.vim

Same as https://github.com/sainnhe/gruvbox-material/pull/144
Instead of re-linking every highlight group to an explicit core group, simply link the old names to the new ones. It reduces redundancy, and is less error prone.
Not applicable

chore(lsp): link old hl groups to new ones

---

colors/everforest.vim

I found the status bar to be too invisible in the default theme, so I bumped up the contrast one level for both the active and inactive status bar backgrounds.
I've been using this for several months and find it a big improvement - without it I frequently don't notice that I'm in a split.
note that there is no visible background to the inactive status bar on top
This is an aesthetic change, so I'll understand and close the PR if you don't like it, but it's one I make on my local installations of your excellent theme.

make status line more visible

---

autoload/everforest.vim

Similar to #108 but for light variants.

Adjust background colors of light variants

---

colors/everforest.vim

Using the "transparent_background=2" option, the current window StatusLine gets filled with carot symbols "^^^" when working in splits. Turns out its default behavior if StatusLine == StatusLineNC [syntax.txt](https://github.com/vim/vim/blob/dd60c365cd2630794be84d63c4fe287124a30b97/runtime/doc/syntax.txt#L5497) 
I just changed the inactive StatusLineNC foreground color to a lighter grey and the carot symbols are gone.
It looks especially annoying in combination with laststatus=3

fix(ui): remove "^^^" from transparent StatusLine in current window

---

colors/everforest.vim

* `'nocombine'` is intentionally omitted; e.g. to preserve italics
before:
after:

fix(plugin): add highlight for context-start to indent-blankline

---

colors/everforest.vim

Adds a definition for `FloatTitle`, which is the default highlight group for neovim floating window titles. Before this change, it would link to `Title` which does not match the float background color.
Before:
After:

feat(ui): add highlight definition for FloatTitle

---

colors/everforest.vim

nvim-treesitter has changed many of its standard captures to better align with the upstream tree-sitter and Helix captures. This adds the new captures whilst leaving the old ones so as not to break back-compatibility.
See [nvim-treesitter@1ae9b0e](https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0)
N/A?

feat(ts): Add new treesitter standard captures

---

colors/everforest.vim

`javascript`, `javascriptreact` and `typescript` have a purple import statement, while `typescriptreact` is red. This PR changes the `typescriptreact` import statement to purple to match the other languages.
Before:
After:

Match tsx 'import' color with typescript/javascript/jsx

---

colors/everforest.vim

Supersedes #136
Fixes https://github.com/sainnhe/gruvbox-material/issues/120
Fixes https://github.com/sainnhe/sonokai/issues/87
Fixes https://github.com/sainnhe/everforest/issues/121 (proper fix, not upstream workaround)
Fixes https://github.com/sainnhe/gruvbox-material/issues/145 (proper fix, not upstream workaround)
Ensures that `LspDiagnostic` and `LspDiagnosticUnderline` use distinct styles: highlighted for the former, underline (undercurl) for the latter.
Rationale:
- If underline is enabled in Neovim, the editor will always use the `LspDiagnosticUnderline` variant.
- By setting a foreground color for the `LspDiagnostic` variant, we ensure that the many popular plugins which leverage these highlight groups default to the correct foreground color.
I have used these settings for a bit …

fix(lsp): use distinct styles for (non-)underline diags

---

colors/everforest.vim

As per the neovim documentation, the `DiagnosticUnnecessary` highlight group corresponds to "unnecessary or unused code." So I think it makes sense to render such code as comments (i.e., dimmed) rather then the default warning with yellow underlines. This is similar to what vscode does I believe, and creates much less visual pollution. 
Before:
After:

Link DiagnosticUnnecessary to TSComment

---

colors/everforest.vim

Add explicit support for all new groups since #69 and for the (hopefully) upcoming 'mini.icons'.

feat(mini): add new highlight groups

---

colors/everforest.vim

See https://github.com/echasnovski/mini.nvim/discussions/1043 for description and screenshots this PR resolves.

fix(mini): fix bg on MiniFilesFile and MiniPickPrompt

---

colors/everforest.vim

adds highlights for the nvim-dap-ui control elements
inactive
inactive, window focused
active
active, window focused
inactive
inactive, window focused
active
active, window focused

feat(plugin): add highlights for nvim-dap-ui controls
